### ISSUE TITLE
Get shell access to container on failure?

### ISSUE THREAD

**Issue by eatonphil** [circleci/local-cli#6]
I'm having a terrible time debugging an installation of a random programming language from source. It would be much easier if I could get shell access to the container on failure. I'm a little confused how the CLI runs Docker containers though. I would have expected a container to linger if I run `docker ps -a`. Maybe the CLI cleans up after itself though? If it didn't I'd be able to `docker commit $(docker ps -a | grep blah | cut -d ' ' -f 1) my-test` sort of thing to save the image and then `docker run` to get a shell. But it doesn't seem to work like that.

Is there an obvious workaround I'm missing?

**Comment by felicianotech** [comment]
Hey Phil!

This type of question is best suited for [CircleCI Discuss](https://discuss.circleci.com) rather than a GitHub Issue. I've answered it [here](https://discuss.circleci.com/t/ssh-to-local-build/19576/8?u=felicianotech).

Since the answer is short though, basically this isn't a feature of the Local CLI. You'll want to "rebuild with SSH" via the CircleCI webapp.

**Comment by eatonphil** [comment]
Got it! Thank you!
